events { }

http {
    include    mime.types;
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html/app;
            index index.html;
        }

        location /odas-config/ {
            alias /usr/share/nginx/html/odas-config/;
        }

        location /assets/ {
            alias /usr/share/nginx/html/assets/;
        }

        #add_header Access-Control-Allow-Origin *;
        #add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
    }
}
